/**
 * Tokenizer parity.
 *
 * The BPE implementation is hand-written, so it gets held to the only standard
 * that matters: identical ids to HuggingFace's own tokenizer for the same
 * model. The reference is generated by tools/embed_ref.py and checked in as
 * fixtures, so this runs without Python.
 *
 * The cases are chosen to break it in the specific ways byte-level BPE breaks:
 * a word with and without a leading space (different tokens), an apostrophe
 * (its own contraction rule), a multi-byte emoji (several byte symbols for one
 * character), a long word that needs many merges, and runs of whitespace.
 */
import { readFileSync } from 'node:fs'
import { BPE } from '../bpe'

const tokenizer = JSON.parse(readFileSync('packs/embed/tokenizer.json', 'utf8'))
const reference: Record<string, { ids: number[] }> = JSON.parse(
  readFileSync('src/packs/__tests__/bpe-reference.json', 'utf8'),
)

const bpe = BPE.fromJson(tokenizer)

let failed = 0
for (const [text, want] of Object.entries(reference)) {
  const got = bpe.encode(text)
  const same = got.length === want.ids.length && got.every((id, i) => id === want.ids[i])
  if (!same) {
    failed++
    console.error(`✗ ${JSON.stringify(text)}\n    want ${want.ids}\n    got  ${got}`)
  }
}

if (failed) {
  console.error(`\n${failed}/${Object.keys(reference).length} tokenizations differ`)
  process.exit(1)
}
console.log(`bpe: ${Object.keys(reference).length}/${Object.keys(reference).length} match reference`)
